stages:
  - zipRuntimeData

zipRuntime:
  - stage: zipRuntimeData
tags:
  - S4-B
script:
  - name="shenhangke"
  - cd ${SHARED_DIR}/Builds/${name}
  - tar -zcvf runtimeData.tar.gz runtime
  - split -b 200m -d runtimeData.tar.gz runtimeData.tar.gz_
when: always