stages:
  - zipContainerInfo

zipContainerInfo:
  stage: zipRuntimeData
  tags:
    - S4-B
  script: 
    - name="shenhangke"
    - cd ${SHARED_DIR}/Builds/${name}/DataReposity
    - tar -zcvf ItemContainerInfo.tar.gz ItemContainerInfo
    - split -b 400m -d runtimeData.tar.gz runtimeData.tar.gz_
  when: always